[plugin]

prepend_preloaders = [
  # Office Documents
  { mime = "application/vnd.openxmlformats-officedocument.*", run = "office" },
  { mime = "application/vnd.oasis.opendocument.*", run = "office" },
  { mime = "application/vnd.ms-*", run = "office" },
  { mime = "application/msword", run = "office" },
  { name = "*.docx", run = "office" },
  # data
  { name = "*.csv", run = "duckdb", multi = false },
  { name = "*.tsv", run = "duckdb", multi = false },
  { name = "*.json", run = "duckdb", multi = false },
  { name = "*.parquet", run = "duckdb", multi = false },
  # { name = "*.txt", run = "duckdb", multi = false },
  { name = "*.xlsx", run = "duckdb", multi = false },
]

prepend_previewers = [
  # Archive previewer
  { mime = "application/*zip", run = "ouch" },
  { mime = "application/x-tar", run = "ouch" },
  { mime = "application/x-bzip2", run = "ouch" },
  { mime = "application/x-7z-compressed", run = "ouch" },
  { mime = "application/x-rar", run = "ouch" },
  { mime = "application/x-xz", run = "ouch" },
  # rich-preview
  { name = "*.md", run = "rich-preview" },    # for markdown (.md) files
  { name = "*.rst", run = "rich-preview" },   # for restructured text (.rst) files
  { name = "*.ipynb", run = "rich-preview" }, # for jupyter notebooks (.ipynb)
  { name = "*.json", run = "rich-preview" },  # for json (.json) files
  #    { name = "*.lang_type", run = "rich-preview"} # for particular language files eg. .py, .go., .lua, etc.
  # data
  { name = "*.csv", run = "duckdb" },
  { name = "*.tsv", run = "duckdb" },
  { name = "*.json", run = "duckdb" },
  { name = "*.parquet", run = "duckdb" },
  { name = "*.root", run = 'piper -- rootls -lr "$1"' },
  # { name = "*.txt", run = "duckdb" },
  { name = "*.xlsx", run = "duckdb" },
  { name = "*.db", run = "duckdb" },
  { name = "*.duckdb", run = "duckdb" },
  # Office Documents
  { mime = "application/vnd.openxmlformats-officedocument.*", run = "office" },
  { mime = "application/vnd.oasis.opendocument.*", run = "office" },
  { mime = "application/vnd.ms-*", run = "office" },
  { mime = "application/msword", run = "office" },
  { name = "*.docx", run = "office" },
  # git
  { name = '**/.git/', run = 'preview-git' },
]

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
